version: '3'

services:

  app-fpm:
    build:
        context: .
        dockerfile: Dockerfile
    env_file: .env
    restart: always
    working_dir: /var/www/wss
    volumes:
      - .:/var/www/wss

  redis-no-auth:
      image: redis:6-alpine
      restart: always
      ports:
          - "0.0.0.0:6679:6379"
      volumes:
          - ./redis.conf:/redis.conf
      command: [ "redis-server", "/redis.conf" ]

  mariadb:
      image: mariadb
      restart: always
      volumes:
          - ./mariadb_data:/var/lib/mysql
          - ./mysql.conf:/etc/mysql/conf.d/mysql.cnf:ro
      environment:
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_USER: ${DB_USERNAME}
          MYSQL_PASSWORD: ${DB_PASSWORD}
      ports:
          - "3309:3306"
